[package]
name = "libtorrent-rasterbar-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
libtorrent-rasterbar-sys = { path = "libtorrent-rasterbar-sys", version = "0.1.0" }
thiserror = "2"
cxx = "1.0"
anyhow = "1.0.95"
