name: Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: build
    runs-on: windows-latest
    continue-on-error: false

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
          filter: tree:0

      - uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          override_cache_key: ccache-windows-build-${{ github.base_ref }}
          ccache_options: |
            max_size=5G

      - name: install boost
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
          cd boost
          bootstrap.bat

      - name: boost headers
        run: |
          cd boost
          .\b2 headers

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: build
        run: |
          set BOOST_ROOT=%CD%\boost
          set PATH=%BOOST_ROOT%;%PATH%
          cargo build
